<Project><PropertyGroup><LangVersion>latest</LangVersion><Nullable>enable</Nullable><Deterministic>true</Deterministic><RestorePackagesWithLockFile>true</RestorePackagesWithLockFile><NuGetAuditMode>all</NuGetAuditMode><Version>1.0.1</Version><AssemblyVersion>1.0.1.0</AssemblyVersion><FileVersion>1.0.1.0</FileVersion><Authors>Akademik Parafraz</Authors><Company>Akademik Parafraz</Company></PropertyGroup></Project>
