<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><TargetFramework>net48</TargetFramework><UseWindowsForms>true</UseWindowsForms><GenerateBindingRedirectsOutputType>true</GenerateBindingRedirectsOutputType><AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects></PropertyGroup><ItemGroup><ProjectReference Include="../AcademicParaphraser.Core/AcademicParaphraser.Core.csproj"/><ProjectReference Include="../AcademicParaphraser.Infrastructure/AcademicParaphraser.Infrastructure.csproj"/><PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.3" PrivateAssets="all"/><PackageReference Include="Microsoft.Office.Interop.Word" Version="15.0.4797.1004"/></ItemGroup><ItemGroup><Reference Include="System.Net.Http"/></ItemGroup></Project>
