<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><TargetFramework>netstandard2.0</TargetFramework></PropertyGroup><ItemGroup><PackageReference Include="Newtonsoft.Json" Version="13.0.3"/></ItemGroup><ItemGroup><EmbeddedResource Include="Data/*.json"/></ItemGroup><ItemGroup><EmbeddedResource Include="../../artifacts/rules/rules.extended.json"><LogicalName>AcademicParaphraser.Core.Data.rules.extended.json</LogicalName></EmbeddedResource></ItemGroup><Target Name="ExpandAcademicRules" BeforeTargets="BeforeBuild"><Exec Command="python &quot;$(MSBuildProjectDirectory)/../../build/Expand-AcademicRules.py&quot;" /></Target></Project>
